export enum NotificationType {
  EMAIL = 'email',
  PUSH = 'push',
}

export enum NotificationStatus {
  PENDING = 'pending',
  DELIVERED = 'delivered',
  FAILED = 'failed',
}

export interface NotificationMessage {
  message_id: string;      // UUID generated by API Gateway
  request_id: string;      // Client's request ID for idempotency
  notification_type: NotificationType;
  user_id: string;         // UUID of the user
  template_code: string;   // e.g., "welcome_email", "password_reset"
  
  // Template variables
  variables: Record<string, unknown>;
  
  // Optional fields
  priority?: number;       // 1=high, 2=medium, 3=low
  metadata?: {
    source?: string;       // e.g., "user_signup", "payment"
    campaign_id?: string;
    [key: string]: string | number | boolean | null | undefined;
  };
  created_at?: string;     // ISO timestamp
  correlation_id?: string; // For distributed tracing
}

export interface ApiResponse<T = unknown> {
  success: boolean;
  data?: T;
  error?: string;
  message: string;
  meta?: PaginationMeta;
}

export interface PaginationMeta {
  total: number;
  limit: number;
  page: number;
  total_pages: number;
  has_next: boolean;
  has_previous: boolean;
}

export interface UserPreference {
  email: boolean;
  push: boolean;
}

export interface UserData {
  id: string;
  name: string;
  email: string;
  push_token?: string;
  preferences: UserPreference;
}

export interface TemplateData {
  id: string;
  code: string;
  subject: string;
  body: string;
  text_version?: string;
  language: string;
  version: number;
}

export interface NotificationStatusUpdate {
  notification_id: string;
  status: NotificationStatus;
  timestamp?: string;
  error?: string;
  provider_response?: {
    message_id?: string;
    success?: boolean;
    [key: string]: string | number | boolean | undefined;
  };
}
