# Generated by Django 5.2.6 on 2026-01-28 10:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("observability", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="gatewaymetrics",
            name="last_updated",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
