# Generated by Django 5.1 on 2026-01-15 10:10

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('templates', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, validators=[django.core.validators.RegexValidator(message='Name must contain only lowercase letters, numbers, hyphens, and underscores', regex='^[a-z0-9_-]+$')])),
                ('template_type', models.CharField(choices=[('welcome', 'Welcome Email'), ('reset_password', 'Password Reset'), ('notification', 'General Notification'), ('promotional', 'Promotional Email'), ('transactional', 'Transactional Email')], max_length=50)),
                ('subject', models.CharField(max_length=500)),
                ('html_content', models.TextField(help_text='HTML template with Handlebars placeholders')),
                ('text_content', models.TextField(blank=True, help_text='Plain text version')),
                ('description', models.TextField(blank=True)),
                ('required_variables', models.JSONField(default=list, help_text='List of required variable names')),
                ('optional_variables', models.JSONField(default=list, help_text='List of optional variable names')),
                ('is_active', models.BooleanField(default=True)),
                ('version', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'db_table': 'email_templates',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TemplateVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_number', models.IntegerField()),
                ('html_content', models.TextField()),
                ('text_content', models.TextField(blank=True)),
                ('subject', models.CharField(max_length=500)),
                ('required_variables', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.CharField(blank=True, max_length=255)),
                ('change_notes', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'template_versions',
                'ordering': ['-version_number'],
            },
        ),
        migrations.DeleteModel(
            name='Template',
        ),
        migrations.AddIndex(
            model_name='emailtemplate',
            index=models.Index(fields=['name'], name='email_templ_name_4bbac9_idx'),
        ),
        migrations.AddIndex(
            model_name='emailtemplate',
            index=models.Index(fields=['template_type'], name='email_templ_templat_90f285_idx'),
        ),
        migrations.AddIndex(
            model_name='emailtemplate',
            index=models.Index(fields=['is_active'], name='email_templ_is_acti_e5b6d1_idx'),
        ),
        migrations.AddField(
            model_name='templateversion',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='templates.emailtemplate'),
        ),
        migrations.AlterUniqueTogether(
            name='templateversion',
            unique_together={('template', 'version_number')},
        ),
    ]
